[RFC] Test NVML linking during build configuration
The NVML library lives in the NVIDIA driver, and using NVML
could cause late linking errors depending on CUDA version requested.
Build detection now bails early if sample NVML API calls cannot be
compiled, alerting users of the possibly outdated display drivers.

FIXME: this is supposed to fix #2311, but it doesn't. In a CUDA 8.0 build
on a machine with no NVIDIA driver try_compile() actually succeeds,
linking against stubs/nvidia-ml.so, while gmx linking still fails:

...
/usr/bin/c++    -march=core-avx2    -std=c++11  -Wundef -Wextra -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wall  -g -fno-inline      CMakeFiles/template.dir/template.cpp.o  -o ../../bin/template ../../lib/libgromacs.so.3.0.0 -fopenmp -lm -Wl,-rpath,"\$ORIGIN/../lib"
/usr/bin/ld: warning: libnvidia-ml.so.1, needed by ../../lib/libgromacs.so.3.0.0, not found (try using -rpath or -rpath-link)
../../lib/libgromacs.so.3.0.0: undefined reference to `nvmlDeviceGetPciInfo_v2'
...

Not sure what is the correct approach here.

Change-Id: If8cf15f68da7af5f9d02d901b956ee2e48703577