Handle Windows path separator in Colvars tests
```
 [ RUN      ] ColvarsOptionsTest.RetrieveEdrFilename
..\src\gromacs\applied_forces\colvars\tests\colvarsoptions.cpp(303): error: Expected equality of these values:
  "output/ener"
  colvarsOptions_.colvarsOutputPrefix()
    Which is: "output\\ener"
```